// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/ha-t2/di-sample/repo"
	"github.com/ha-t2/di-sample/service"
)

// Injectors from wire.go:

func InitializeProductService() service.ProductService {
	productRepoInterface := repo.NewProductRepo()
	productService := service.NewProductService(productRepoInterface)
	return productService
}
